services:
  postgres-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'

volumes:
  postgres-db-data:
