services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp
      POSTGRES_DB: erp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
