services:
  postgres-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'

  otel-lgtm:
    image: grafana/otel-lgtm:latest
    restart: always
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3000:3000"

volumes:
  postgres-db-data:
