name = "erp-system-web"
compatibility_date = "2025-07-12"
main = "src/worker.ts"

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[observability.logs]
enabled = true
