/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedNewOrgRouteImport } from './routes/_authed/new-org'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as AuthedOrgOrgSlugRouteImport } from './routes/_authed/org/$orgSlug'
import { Route as AuthedOrgOrgSlugIndexRouteImport } from './routes/_authed/org/$orgSlug/index'
import { Route as AuthedOrgOrgSlugMembersRouteImport } from './routes/_authed/org/$orgSlug/members'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNewOrgRoute = AuthedNewOrgRouteImport.update({
  id: '/new-org',
  path: '/new-org',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgOrgSlugRoute = AuthedOrgOrgSlugRouteImport.update({
  id: '/org/$orgSlug',
  path: '/org/$orgSlug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgOrgSlugIndexRoute = AuthedOrgOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgOrgSlugRoute,
} as any)
const AuthedOrgOrgSlugMembersRoute = AuthedOrgOrgSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedOrgOrgSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthedHomeRoute
  '/new-org': typeof AuthedNewOrgRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/org/$orgSlug': typeof AuthedOrgOrgSlugRouteWithChildren
  '/org/$orgSlug/members': typeof AuthedOrgOrgSlugMembersRoute
  '/org/$orgSlug/': typeof AuthedOrgOrgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthedHomeRoute
  '/new-org': typeof AuthedNewOrgRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/org/$orgSlug/members': typeof AuthedOrgOrgSlugMembersRoute
  '/org/$orgSlug': typeof AuthedOrgOrgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/new-org': typeof AuthedNewOrgRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/org/$orgSlug': typeof AuthedOrgOrgSlugRouteWithChildren
  '/_authed/org/$orgSlug/members': typeof AuthedOrgOrgSlugMembersRoute
  '/_authed/org/$orgSlug/': typeof AuthedOrgOrgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/new-org'
    | '/onboarding'
    | '/org/$orgSlug'
    | '/org/$orgSlug/members'
    | '/org/$orgSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/new-org'
    | '/onboarding'
    | '/org/$orgSlug/members'
    | '/org/$orgSlug'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/home'
    | '/_authed/new-org'
    | '/_authed/onboarding'
    | '/_authed/org/$orgSlug'
    | '/_authed/org/$orgSlug/members'
    | '/_authed/org/$orgSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/new-org': {
      id: '/_authed/new-org'
      path: '/new-org'
      fullPath: '/new-org'
      preLoaderRoute: typeof AuthedNewOrgRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/$orgSlug': {
      id: '/_authed/org/$orgSlug'
      path: '/org/$orgSlug'
      fullPath: '/org/$orgSlug'
      preLoaderRoute: typeof AuthedOrgOrgSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/$orgSlug/': {
      id: '/_authed/org/$orgSlug/'
      path: '/'
      fullPath: '/org/$orgSlug/'
      preLoaderRoute: typeof AuthedOrgOrgSlugIndexRouteImport
      parentRoute: typeof AuthedOrgOrgSlugRoute
    }
    '/_authed/org/$orgSlug/members': {
      id: '/_authed/org/$orgSlug/members'
      path: '/members'
      fullPath: '/org/$orgSlug/members'
      preLoaderRoute: typeof AuthedOrgOrgSlugMembersRouteImport
      parentRoute: typeof AuthedOrgOrgSlugRoute
    }
  }
}

interface AuthedOrgOrgSlugRouteChildren {
  AuthedOrgOrgSlugMembersRoute: typeof AuthedOrgOrgSlugMembersRoute
  AuthedOrgOrgSlugIndexRoute: typeof AuthedOrgOrgSlugIndexRoute
}

const AuthedOrgOrgSlugRouteChildren: AuthedOrgOrgSlugRouteChildren = {
  AuthedOrgOrgSlugMembersRoute: AuthedOrgOrgSlugMembersRoute,
  AuthedOrgOrgSlugIndexRoute: AuthedOrgOrgSlugIndexRoute,
}

const AuthedOrgOrgSlugRouteWithChildren =
  AuthedOrgOrgSlugRoute._addFileChildren(AuthedOrgOrgSlugRouteChildren)

interface AuthedRouteChildren {
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedNewOrgRoute: typeof AuthedNewOrgRoute
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedOrgOrgSlugRoute: typeof AuthedOrgOrgSlugRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedNewOrgRoute: AuthedNewOrgRoute,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedOrgOrgSlugRoute: AuthedOrgOrgSlugRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
