/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PubRouteRouteImport } from './routes/_pub/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as PubIndexRouteImport } from './routes/_pub/index'
import { Route as PubSignupRouteImport } from './routes/_pub/signup'
import { Route as PubLoginRouteImport } from './routes/_pub/login'
import { Route as AuthedAppRouteRouteImport } from './routes/_authed/_app/route'
import { Route as AuthedAppOnboardingRouteImport } from './routes/_authed/_app/onboarding'
import { Route as AuthedAppNewOrgRouteImport } from './routes/_authed/_app/new-org'
import { Route as AuthedAppHomeRouteImport } from './routes/_authed/_app/home'
import { Route as AuthedOrgOrgSlugRouteRouteImport } from './routes/_authed/org.$orgSlug/route'
import { Route as AuthedOrgOrgSlugIndexRouteImport } from './routes/_authed/org.$orgSlug/index'
import { Route as AuthedOrgOrgSlugMembersRouteImport } from './routes/_authed/org.$orgSlug/members'

const PubRouteRoute = PubRouteRouteImport.update({
  id: '/_pub',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PubIndexRoute = PubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PubRouteRoute,
} as any)
const PubSignupRoute = PubSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PubRouteRoute,
} as any)
const PubLoginRoute = PubLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PubRouteRoute,
} as any)
const AuthedAppRouteRoute = AuthedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAppOnboardingRoute = AuthedAppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedAppRouteRoute,
} as any)
const AuthedAppNewOrgRoute = AuthedAppNewOrgRouteImport.update({
  id: '/new-org',
  path: '/new-org',
  getParentRoute: () => AuthedAppRouteRoute,
} as any)
const AuthedAppHomeRoute = AuthedAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedAppRouteRoute,
} as any)
const AuthedOrgOrgSlugRouteRoute = AuthedOrgOrgSlugRouteRouteImport.update({
  id: '/org/$orgSlug',
  path: '/org/$orgSlug',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrgOrgSlugIndexRoute = AuthedOrgOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgOrgSlugRouteRoute,
} as any)
const AuthedOrgOrgSlugMembersRoute = AuthedOrgOrgSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedOrgOrgSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PubIndexRoute
  '/login': typeof PubLoginRoute
  '/signup': typeof PubSignupRoute
  '/org/$orgSlug': typeof AuthedOrgOrgSlugRouteRouteWithChildren
  '/home': typeof AuthedAppHomeRoute
  '/new-org': typeof AuthedAppNewOrgRoute
  '/onboarding': typeof AuthedAppOnboardingRoute
  '/org/$orgSlug/members': typeof AuthedOrgOrgSlugMembersRoute
  '/org/$orgSlug/': typeof AuthedOrgOrgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PubIndexRoute
  '/login': typeof PubLoginRoute
  '/signup': typeof PubSignupRoute
  '/home': typeof AuthedAppHomeRoute
  '/new-org': typeof AuthedAppNewOrgRoute
  '/onboarding': typeof AuthedAppOnboardingRoute
  '/org/$orgSlug/members': typeof AuthedOrgOrgSlugMembersRoute
  '/org/$orgSlug': typeof AuthedOrgOrgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_pub': typeof PubRouteRouteWithChildren
  '/_authed/_app': typeof AuthedAppRouteRouteWithChildren
  '/_pub/login': typeof PubLoginRoute
  '/_pub/signup': typeof PubSignupRoute
  '/_pub/': typeof PubIndexRoute
  '/_authed/org/$orgSlug': typeof AuthedOrgOrgSlugRouteRouteWithChildren
  '/_authed/_app/home': typeof AuthedAppHomeRoute
  '/_authed/_app/new-org': typeof AuthedAppNewOrgRoute
  '/_authed/_app/onboarding': typeof AuthedAppOnboardingRoute
  '/_authed/org/$orgSlug/members': typeof AuthedOrgOrgSlugMembersRoute
  '/_authed/org/$orgSlug/': typeof AuthedOrgOrgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/org/$orgSlug'
    | '/home'
    | '/new-org'
    | '/onboarding'
    | '/org/$orgSlug/members'
    | '/org/$orgSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/new-org'
    | '/onboarding'
    | '/org/$orgSlug/members'
    | '/org/$orgSlug'
  id:
    | '__root__'
    | '/_authed'
    | '/_pub'
    | '/_authed/_app'
    | '/_pub/login'
    | '/_pub/signup'
    | '/_pub/'
    | '/_authed/org/$orgSlug'
    | '/_authed/_app/home'
    | '/_authed/_app/new-org'
    | '/_authed/_app/onboarding'
    | '/_authed/org/$orgSlug/members'
    | '/_authed/org/$orgSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PubRouteRoute: typeof PubRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pub': {
      id: '/_pub'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PubRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pub/': {
      id: '/_pub/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PubIndexRouteImport
      parentRoute: typeof PubRouteRoute
    }
    '/_pub/signup': {
      id: '/_pub/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PubSignupRouteImport
      parentRoute: typeof PubRouteRoute
    }
    '/_pub/login': {
      id: '/_pub/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PubLoginRouteImport
      parentRoute: typeof PubRouteRoute
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/_app/onboarding': {
      id: '/_authed/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedAppOnboardingRouteImport
      parentRoute: typeof AuthedAppRouteRoute
    }
    '/_authed/_app/new-org': {
      id: '/_authed/_app/new-org'
      path: '/new-org'
      fullPath: '/new-org'
      preLoaderRoute: typeof AuthedAppNewOrgRouteImport
      parentRoute: typeof AuthedAppRouteRoute
    }
    '/_authed/_app/home': {
      id: '/_authed/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedAppHomeRouteImport
      parentRoute: typeof AuthedAppRouteRoute
    }
    '/_authed/org/$orgSlug': {
      id: '/_authed/org/$orgSlug'
      path: '/org/$orgSlug'
      fullPath: '/org/$orgSlug'
      preLoaderRoute: typeof AuthedOrgOrgSlugRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/org/$orgSlug/': {
      id: '/_authed/org/$orgSlug/'
      path: '/'
      fullPath: '/org/$orgSlug/'
      preLoaderRoute: typeof AuthedOrgOrgSlugIndexRouteImport
      parentRoute: typeof AuthedOrgOrgSlugRouteRoute
    }
    '/_authed/org/$orgSlug/members': {
      id: '/_authed/org/$orgSlug/members'
      path: '/members'
      fullPath: '/org/$orgSlug/members'
      preLoaderRoute: typeof AuthedOrgOrgSlugMembersRouteImport
      parentRoute: typeof AuthedOrgOrgSlugRouteRoute
    }
  }
}

interface AuthedAppRouteRouteChildren {
  AuthedAppHomeRoute: typeof AuthedAppHomeRoute
  AuthedAppNewOrgRoute: typeof AuthedAppNewOrgRoute
  AuthedAppOnboardingRoute: typeof AuthedAppOnboardingRoute
}

const AuthedAppRouteRouteChildren: AuthedAppRouteRouteChildren = {
  AuthedAppHomeRoute: AuthedAppHomeRoute,
  AuthedAppNewOrgRoute: AuthedAppNewOrgRoute,
  AuthedAppOnboardingRoute: AuthedAppOnboardingRoute,
}

const AuthedAppRouteRouteWithChildren = AuthedAppRouteRoute._addFileChildren(
  AuthedAppRouteRouteChildren,
)

interface AuthedOrgOrgSlugRouteRouteChildren {
  AuthedOrgOrgSlugMembersRoute: typeof AuthedOrgOrgSlugMembersRoute
  AuthedOrgOrgSlugIndexRoute: typeof AuthedOrgOrgSlugIndexRoute
}

const AuthedOrgOrgSlugRouteRouteChildren: AuthedOrgOrgSlugRouteRouteChildren = {
  AuthedOrgOrgSlugMembersRoute: AuthedOrgOrgSlugMembersRoute,
  AuthedOrgOrgSlugIndexRoute: AuthedOrgOrgSlugIndexRoute,
}

const AuthedOrgOrgSlugRouteRouteWithChildren =
  AuthedOrgOrgSlugRouteRoute._addFileChildren(
    AuthedOrgOrgSlugRouteRouteChildren,
  )

interface AuthedRouteRouteChildren {
  AuthedAppRouteRoute: typeof AuthedAppRouteRouteWithChildren
  AuthedOrgOrgSlugRouteRoute: typeof AuthedOrgOrgSlugRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAppRouteRoute: AuthedAppRouteRouteWithChildren,
  AuthedOrgOrgSlugRouteRoute: AuthedOrgOrgSlugRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface PubRouteRouteChildren {
  PubLoginRoute: typeof PubLoginRoute
  PubSignupRoute: typeof PubSignupRoute
  PubIndexRoute: typeof PubIndexRoute
}

const PubRouteRouteChildren: PubRouteRouteChildren = {
  PubLoginRoute: PubLoginRoute,
  PubSignupRoute: PubSignupRoute,
  PubIndexRoute: PubIndexRoute,
}

const PubRouteRouteWithChildren = PubRouteRoute._addFileChildren(
  PubRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PubRouteRoute: PubRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
