/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgRouteImport } from './routes/org'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgOrgSlugIndexRouteImport } from './routes/org.$orgSlug/index'
import { Route as OrgOrgSlugUsersRouteImport } from './routes/org.$orgSlug/users'
import { Route as OrgOrgSlugTransactionsRouteImport } from './routes/org.$orgSlug/transactions'
import { Route as OrgOrgSlugProductsRouteImport } from './routes/org.$orgSlug/products'
import { Route as OrgOrgSlugInvoicesRouteImport } from './routes/org.$orgSlug/invoices'
import { Route as OrgOrgSlugExpensesRouteImport } from './routes/org.$orgSlug/expenses'
import { Route as OrgOrgSlugCustomersRouteImport } from './routes/org.$orgSlug/customers'
import { Route as OrgOrgSlugCreateInvoiceRouteImport } from './routes/org.$orgSlug/create-invoice'

const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgSlugIndexRoute = OrgOrgSlugIndexRouteImport.update({
  id: '/$orgSlug/',
  path: '/$orgSlug/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrgSlugUsersRoute = OrgOrgSlugUsersRouteImport.update({
  id: '/$orgSlug/users',
  path: '/$orgSlug/users',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrgSlugTransactionsRoute = OrgOrgSlugTransactionsRouteImport.update({
  id: '/$orgSlug/transactions',
  path: '/$orgSlug/transactions',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrgSlugProductsRoute = OrgOrgSlugProductsRouteImport.update({
  id: '/$orgSlug/products',
  path: '/$orgSlug/products',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrgSlugInvoicesRoute = OrgOrgSlugInvoicesRouteImport.update({
  id: '/$orgSlug/invoices',
  path: '/$orgSlug/invoices',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrgSlugExpensesRoute = OrgOrgSlugExpensesRouteImport.update({
  id: '/$orgSlug/expenses',
  path: '/$orgSlug/expenses',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrgSlugCustomersRoute = OrgOrgSlugCustomersRouteImport.update({
  id: '/$orgSlug/customers',
  path: '/$orgSlug/customers',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrgSlugCreateInvoiceRoute = OrgOrgSlugCreateInvoiceRouteImport.update({
  id: '/$orgSlug/create-invoice',
  path: '/$orgSlug/create-invoice',
  getParentRoute: () => OrgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/org': typeof OrgRouteWithChildren
  '/org/$orgSlug/create-invoice': typeof OrgOrgSlugCreateInvoiceRoute
  '/org/$orgSlug/customers': typeof OrgOrgSlugCustomersRoute
  '/org/$orgSlug/expenses': typeof OrgOrgSlugExpensesRoute
  '/org/$orgSlug/invoices': typeof OrgOrgSlugInvoicesRoute
  '/org/$orgSlug/products': typeof OrgOrgSlugProductsRoute
  '/org/$orgSlug/transactions': typeof OrgOrgSlugTransactionsRoute
  '/org/$orgSlug/users': typeof OrgOrgSlugUsersRoute
  '/org/$orgSlug': typeof OrgOrgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/org': typeof OrgRouteWithChildren
  '/org/$orgSlug/create-invoice': typeof OrgOrgSlugCreateInvoiceRoute
  '/org/$orgSlug/customers': typeof OrgOrgSlugCustomersRoute
  '/org/$orgSlug/expenses': typeof OrgOrgSlugExpensesRoute
  '/org/$orgSlug/invoices': typeof OrgOrgSlugInvoicesRoute
  '/org/$orgSlug/products': typeof OrgOrgSlugProductsRoute
  '/org/$orgSlug/transactions': typeof OrgOrgSlugTransactionsRoute
  '/org/$orgSlug/users': typeof OrgOrgSlugUsersRoute
  '/org/$orgSlug': typeof OrgOrgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/org': typeof OrgRouteWithChildren
  '/org/$orgSlug/create-invoice': typeof OrgOrgSlugCreateInvoiceRoute
  '/org/$orgSlug/customers': typeof OrgOrgSlugCustomersRoute
  '/org/$orgSlug/expenses': typeof OrgOrgSlugExpensesRoute
  '/org/$orgSlug/invoices': typeof OrgOrgSlugInvoicesRoute
  '/org/$orgSlug/products': typeof OrgOrgSlugProductsRoute
  '/org/$orgSlug/transactions': typeof OrgOrgSlugTransactionsRoute
  '/org/$orgSlug/users': typeof OrgOrgSlugUsersRoute
  '/org/$orgSlug/': typeof OrgOrgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/org'
    | '/org/$orgSlug/create-invoice'
    | '/org/$orgSlug/customers'
    | '/org/$orgSlug/expenses'
    | '/org/$orgSlug/invoices'
    | '/org/$orgSlug/products'
    | '/org/$orgSlug/transactions'
    | '/org/$orgSlug/users'
    | '/org/$orgSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/org'
    | '/org/$orgSlug/create-invoice'
    | '/org/$orgSlug/customers'
    | '/org/$orgSlug/expenses'
    | '/org/$orgSlug/invoices'
    | '/org/$orgSlug/products'
    | '/org/$orgSlug/transactions'
    | '/org/$orgSlug/users'
    | '/org/$orgSlug'
  id:
    | '__root__'
    | '/'
    | '/org'
    | '/org/$orgSlug/create-invoice'
    | '/org/$orgSlug/customers'
    | '/org/$orgSlug/expenses'
    | '/org/$orgSlug/invoices'
    | '/org/$orgSlug/products'
    | '/org/$orgSlug/transactions'
    | '/org/$orgSlug/users'
    | '/org/$orgSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgRoute: typeof OrgRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgSlug/': {
      id: '/org/$orgSlug/'
      path: '/$orgSlug'
      fullPath: '/org/$orgSlug'
      preLoaderRoute: typeof OrgOrgSlugIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/$orgSlug/users': {
      id: '/org/$orgSlug/users'
      path: '/$orgSlug/users'
      fullPath: '/org/$orgSlug/users'
      preLoaderRoute: typeof OrgOrgSlugUsersRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/$orgSlug/transactions': {
      id: '/org/$orgSlug/transactions'
      path: '/$orgSlug/transactions'
      fullPath: '/org/$orgSlug/transactions'
      preLoaderRoute: typeof OrgOrgSlugTransactionsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/$orgSlug/products': {
      id: '/org/$orgSlug/products'
      path: '/$orgSlug/products'
      fullPath: '/org/$orgSlug/products'
      preLoaderRoute: typeof OrgOrgSlugProductsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/$orgSlug/invoices': {
      id: '/org/$orgSlug/invoices'
      path: '/$orgSlug/invoices'
      fullPath: '/org/$orgSlug/invoices'
      preLoaderRoute: typeof OrgOrgSlugInvoicesRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/$orgSlug/expenses': {
      id: '/org/$orgSlug/expenses'
      path: '/$orgSlug/expenses'
      fullPath: '/org/$orgSlug/expenses'
      preLoaderRoute: typeof OrgOrgSlugExpensesRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/$orgSlug/customers': {
      id: '/org/$orgSlug/customers'
      path: '/$orgSlug/customers'
      fullPath: '/org/$orgSlug/customers'
      preLoaderRoute: typeof OrgOrgSlugCustomersRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/$orgSlug/create-invoice': {
      id: '/org/$orgSlug/create-invoice'
      path: '/$orgSlug/create-invoice'
      fullPath: '/org/$orgSlug/create-invoice'
      preLoaderRoute: typeof OrgOrgSlugCreateInvoiceRouteImport
      parentRoute: typeof OrgRoute
    }
  }
}

interface OrgRouteChildren {
  OrgOrgSlugCreateInvoiceRoute: typeof OrgOrgSlugCreateInvoiceRoute
  OrgOrgSlugCustomersRoute: typeof OrgOrgSlugCustomersRoute
  OrgOrgSlugExpensesRoute: typeof OrgOrgSlugExpensesRoute
  OrgOrgSlugInvoicesRoute: typeof OrgOrgSlugInvoicesRoute
  OrgOrgSlugProductsRoute: typeof OrgOrgSlugProductsRoute
  OrgOrgSlugTransactionsRoute: typeof OrgOrgSlugTransactionsRoute
  OrgOrgSlugUsersRoute: typeof OrgOrgSlugUsersRoute
  OrgOrgSlugIndexRoute: typeof OrgOrgSlugIndexRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgOrgSlugCreateInvoiceRoute: OrgOrgSlugCreateInvoiceRoute,
  OrgOrgSlugCustomersRoute: OrgOrgSlugCustomersRoute,
  OrgOrgSlugExpensesRoute: OrgOrgSlugExpensesRoute,
  OrgOrgSlugInvoicesRoute: OrgOrgSlugInvoicesRoute,
  OrgOrgSlugProductsRoute: OrgOrgSlugProductsRoute,
  OrgOrgSlugTransactionsRoute: OrgOrgSlugTransactionsRoute,
  OrgOrgSlugUsersRoute: OrgOrgSlugUsersRoute,
  OrgOrgSlugIndexRoute: OrgOrgSlugIndexRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgRoute: OrgRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
