name: "cleanup-db-cron"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - run: deno task --filter server prisma:generate
      - run: deno run -A ./packages/server/scripts/cleanup-db.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NO_DELETE_ORGS: ${{ secrets.NO_DELETE_ORGS }}
