name: deploy web

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy-web.yml'
      - 'packages/web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g corepack
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: pnpm build:utils
      - run: echo 'API_HOST=${{ secrets.API_HOST }}' > packages/web/.dev.vars
      - run: pnpm web build
      - uses: cloudflare/wrangler-action@v3
        with:
          command: deploy
          workingDirectory: 'packages/web'
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
